name: barracuda_campus
description: The client of Barracuda Campus.
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

resolution: workspace

dependencies:
  cookie_jar: ^4.0.0
  dio: ^5.0.0
  dio_cookie_manager: ^3.0.0
  html: ^0.15.0
  intl: any

dev_dependencies:
  lints: ^6.0.0
