name: barracuda_campus
description: The client of Barracuda Campus.
version: 0.0.1
homepage: https://github.com/XMUMY/XMUX

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cookie_jar: ^3.0.0
  dio: ">=4.0.0 <6.0.0"
  dio_cookie_manager: ^2.0.0
  html: ^0.15.0
  intl: ^0.18.0

dev_dependencies:
  lints: ^1.0.0
