name: xmux_client
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

workspace:
  - packages/aaos
  - packages/barracuda_campus
  - packages/emgs
  - packages/maintenance
  - packages/moodle
  - packages/xmus_client
  - packages/xmux
