name: image_cdn
description: Image CDN.
version: 0.0.1
homepage: https://github.com/XMUMY/XMUX

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cookie_jar: ^4.0.0
  dio: ^5.0.0
  dio_cookie_manager: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
