name: image_cdn
description: Image CDN.
version: 0.0.1
homepage: https://github.com/XMUMY/XMUX

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
