name: xmus_client
description: Dart client of XMUS services.
version: 0.0.1
homepage: https://github.com/XMUMY/XMUX

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  grpc: ^3.0.0
  protobuf: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
