name: maintenance
description: The client of AskA Maintenance.
version: 0.0.1
homepage: https://github.com/XMUMY/XMUX

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cookie_jar: ^4.0.0
  dio: ^5.0.0
  html: ^0.15.0
  intl: ^0.18.0
  mobx: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^2.0.0
  mobx_codegen: ^2.0.0
