name: moodle
description: A client of moodle web service API.
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

resolution: workspace

dependencies:
  dio: ^5.0.0
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  lints: ^6.0.0
