name: aaos
description: A client of Academic Affair Online System.
version: 0.0.1
homepage: https://github.com/XMUMY/XMUX

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cookie_jar: ^4.0.0
  dio: ^5.0.0
  dio_cookie_manager: ^3.0.0
  html: ^0.15.0
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  lints: ^5.0.0
  test: ^1.16.0
