# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :internal do
  disable_automatic_code_signing(path: "Runner.xcodeproj")
  create_keychain(
    name: "fastlane",
    password: ENV["MATCH_PASSWORD"],
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )
  match(
    type: "development",
    readonly: true,
    keychain_name: "fastlane",
    keychain_password: ENV["MATCH_PASSWORD"],
  )
  match(
    type: "appstore",
    readonly: true,
    keychain_name: "fastlane",
    keychain_password: ENV["MATCH_PASSWORD"],
  )
  update_project_provisioning(
    xcodeproj: "Runner.xcodeproj",
    profile: ENV["sigh_org.ctbeta.xmux_development_profile-path"],
    target_filter: "Runner",
    build_configuration: "Release"
  )
  build_ios_app(
    workspace: "Runner.xcworkspace",
    scheme: "Runner",
    export_method: "app-store"
  )
  upload_to_testflight
end
