# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new internal build to TestFlight"
  lane :internal do
    update_code_signing_settings(
      use_automatic_signing: false,
    )
    create_keychain(
      name: "fastlane",
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false,
    )
    sync_code_signing(
      type: "development",
      readonly: true,
      keychain_name: "fastlane",
      keychain_password: ENV["MATCH_PASSWORD"],
    )
    sync_code_signing(
      type: "appstore",
      readonly: true,
      keychain_name: "fastlane",
      keychain_password: ENV["MATCH_PASSWORD"],
    )
    update_project_provisioning(
      xcodeproj: "Runner.xcodeproj",
      profile: ENV["sigh_org.ctbeta.xmux_development_profile-path"],
      target_filter: "Runner",
      build_configuration: "Release",
    )
    build_ios_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
    )
    upload_to_testflight(
      api_key_path: "APP_STORE_CONNECT_API_KEY.json",
      skip_waiting_for_build_processing: true,
    )
  end
end
