// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBglRGvbba0G9C99Kq21WFAG5OCp3ZROFw',
    appId: '1:899332542714:web:cd01bc52aa4cae98c4b943',
    messagingSenderId: '899332542714',
    projectId: 'xmux-app',
    authDomain: 'xmux-app.firebaseapp.com',
    databaseURL: 'https://xmux-app.firebaseio.com',
    storageBucket: 'xmux-app.appspot.com',
    measurementId: 'G-Q22TEK7T9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8H7CaRiVZyYAQFPttdo1oOOBgzewq2yo',
    appId: '1:899332542714:android:f56bf7f6fc38085f',
    messagingSenderId: '899332542714',
    projectId: 'xmux-app',
    databaseURL: 'https://xmux-app.firebaseio.com',
    storageBucket: 'xmux-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNXewQrwTNedBQfuHfyAbqBNUScRM54Q4',
    appId: '1:899332542714:ios:991c36fbe7ed3c3a',
    messagingSenderId: '899332542714',
    projectId: 'xmux-app',
    databaseURL: 'https://xmux-app.firebaseio.com',
    storageBucket: 'xmux-app.appspot.com',
    androidClientId: '899332542714-krdj4p2q3saldjs033dc43akhcvgj8lr.apps.googleusercontent.com',
    iosClientId: '899332542714-3tbdio70pe0il4dg5vk40n60cc95krih.apps.googleusercontent.com',
    iosBundleId: 'org.ctbeta.xmux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNXewQrwTNedBQfuHfyAbqBNUScRM54Q4',
    appId: '1:899332542714:ios:991c36fbe7ed3c3a',
    messagingSenderId: '899332542714',
    projectId: 'xmux-app',
    databaseURL: 'https://xmux-app.firebaseio.com',
    storageBucket: 'xmux-app.appspot.com',
    androidClientId: '899332542714-krdj4p2q3saldjs033dc43akhcvgj8lr.apps.googleusercontent.com',
    iosClientId: '899332542714-3tbdio70pe0il4dg5vk40n60cc95krih.apps.googleusercontent.com',
    iosBundleId: 'org.ctbeta.xmux',
  );
}
