name: emgs
description: The client of Education Malaysia Global Services.
version: 0.0.1
homepage: https://github.com/XMUMY/XMUX

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.0.0
  intl: ^0.19.0
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  lints: ^5.0.0
