name: XMUX Android Internal

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/android.yaml
      - lib/**
      - android/**
      - pubspec.yaml
      - pubspec.lock

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "11"
          java-package: jdk
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - name: Build
        run: |
          echo $CONFIG_FILE | base64 -d > lib/config.dart
          echo "${GOOGLE_SERVICES_ANDROID}" > ./android/app/google-services.json
          echo "${ANDROID_RELEASE_SIGN_KEY}" | base64 -d > ./android/app/x.jks
          echo "${ANDROID_RELEASE_SIGN_KEY_PROPERTYS}" | base64 -d > ./android/app/key.properties
          flutter build apk --release --target-platform=android-arm64
        env:
          CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
          GOOGLE_SERVICES_ANDROID: ${{ secrets.GOOGLE_SERVICES_ANDROID }}
          ANDROID_RELEASE_SIGN_KEY: ${{ secrets.ANDROID_RELEASE_SIGN_KEY }}
          ANDROID_RELEASE_SIGN_KEY_PROPERTYS: ${{ secrets.ANDROID_RELEASE_SIGN_KEY_PROPERTYS }}
      - uses: actions/upload-artifact@v3
        with:
          name: XMUX-Android
          path: build/app/outputs/flutter-apk/app-release.apk
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: XMUX-Android
      - uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_KEY }}
          packageName: org.ctbeta.xmux.xmux
          releaseFiles: app-release.apk
          track: internal
