name: XMUX Android Internal

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/android.yaml
      - lib/**
      - android/**
      - pubspec.yaml
      - pubspec.lock

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: "17"
          java-package: jdk
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - name: Build
        run: |
          FLUTTER_BUILD_NUMBER=$(git rev-list --count HEAD)
          GIT_DESC=$(git describe --tags)
          if [[ $GIT_DESC =~ v([0-9]+)\.([0-9]+)\.([0-9]+)-([0-9]+)-g[a-f0-9]+ ]]; then
              FLUTTER_BUILD_NAME="${BASH_REMATCH[1]}.$((BASH_REMATCH[2]+1)).${BASH_REMATCH[3]}"
          else
              FLUTTER_BUILD_NAME="0.0.1"
          fi

          echo $CONFIG_ENV | base64 -d > .env
          echo $ANDROID_RELEASE_SIGN_KEY | base64 -d > ./android/app/x.jks

          flutter build apk \
            --release \
            --build-name=$FLUTTER_BUILD_NAME \
            --build-number=$FLUTTER_BUILD_NUMBER \
            --dart-define-from-file=.env
        env:
          CONFIG_ENV: ${{ secrets.CONFIG_ENV }}
          ANDROID_RELEASE_SIGN_KEY: ${{ secrets.ANDROID_RELEASE_SIGN_KEY }}
          KEYSTORE_FILE: x.jks
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_SIGN_KEYSTORE_PASSWORD }}
          KEY_ALIAS: xmux
          KEY_PASSWORD: ${{ secrets.ANDROID_RELEASE_SIGN_KEY_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: XMUX-Android
          path: build/app/outputs/flutter-apk/app-release.apk

  DeployGooglePlay:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: XMUX-Android
      - uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_KEY }}
          packageName: org.ctbeta.xmux.xmux
          releaseFiles: app-release.apk
          track: internal
