name: XMUX-iOS

on:
  push:
    branches:
      - master

jobs:
  Archive:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - name: Build App
        run: |
          echo $CONFIG_FILE | base64 -d > lib/config.dart
          echo $GOOGLE_SERVICES_IOS > ./ios/GoogleService-Info.plist
          flutter build ios \
            --release \
            --build-name=`cat ./lib/config.sample.dart | grep fallbackVersionName | sed -e "s/[A-z=;' ]//g" | sed "s/-//g"` \
            --build-number=`git rev-list HEAD --count` \
            --no-codesign
        env:
          CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
          GOOGLE_SERVICES_IOS: ${{ secrets.GOOGLE_SERVICES_IOS }}
#      - name: Archive to TestFlight
#        uses: maierj/fastlane-action@v1.4.0
#        with:
#          lane: "internal"
#          subdirectory: "ios"
#        env:
#          FASTLANE_PASSWORD: ${{ secrets.IOS_FASTLANE_PASSWORD }}
#          FASTLANE_DONT_STORE_PASSWORD: "1"
#          MATCH_GIT_PRIVATE_KEY: ${{ secrets.DEPLOY_CERTS }}
#          MATCH_PASSWORD: ${{ secrets.IOS_MATCH_PASSWORD }}
