name: XMUX-iOS

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/ios.yaml
      - lib/**
      - ios/**
      - pubspec.yaml
      - pubspec.lock

jobs:
  Archive:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Prepare Build
        run: |
          echo $CONFIG_FILE | base64 -d > lib/config.dart
          echo $GOOGLE_SERVICES_IOS > ./ios/GoogleService-Info.plist
          export FLUTTER_BUILD_NAME=`cat ./lib/config.sample.dart | grep fallbackVersionName | sed -e "s/[A-z=;' ]//g" | sed "s/-//g"`
          export FLUTTER_BUILD_NUMBER=`git rev-list HEAD --count`
          flutter pub get
          cd ios
          echo $APP_STORE_CONNECT_API_KEY | base64 -d > APP_STORE_CONNECT_API_KEY.json
          pod install
        env:
          CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
          GOOGLE_SERVICES_IOS: ${{ secrets.GOOGLE_SERVICES_IOS }}
      - name: Archive to TestFlight
        uses: maierj/fastlane-action@v2.2.1
        with:
          lane: "internal"
          subdirectory: "ios"
        env:
          FASTLANE_DONT_STORE_PASSWORD: "1"
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.DEPLOY_CERTS }}
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
