name: XMUX-macOS

on:
  push:
    branches:
      - master
    paths:
      - lib/**
      - macos/**
      - pubspec.yaml
      - pubspec.lock

jobs:
  Archive:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - name: Build App
        run: |
          echo $CONFIG_FILE | base64 -d > lib/config.dart
          echo $GOOGLE_SERVICES_IOS > ./macos/GoogleService-Info.plist
          flutter config --enable-macos-desktop && flutter build macos \
            --release \
            --build-name=`cat ./lib/config.sample.dart | grep fallbackVersionName | sed -e "s/[A-z=;' ]//g" | sed "s/-//g"` \
            --build-number=`git rev-list HEAD --count`
        env:
          CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
          GOOGLE_SERVICES_IOS: ${{ secrets.GOOGLE_SERVICES_IOS }}
      - uses: actions/upload-artifact@v2
        with:
          name: XMUX-macOS
          path: build/macos/Build/Products/Release/XMUX.app
