name: XMUX-Web

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - name: Build
        run: |
          echo $CONFIG_FILE | base64 -d > lib/config.dart
          echo $WEB_INDEX | base64 -d > web/index.html
          flutter config --enable-web && flutter build web --release
        env:
          CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
          WEB_INDEX: ${{ secrets.WEB_INDEX }}
      - uses: actions/upload-artifact@v1
        with:
          name: XMUX-Web
          path: build/web

  DeployGithubStatic:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: XMUX-Web
      - name: Replace main.dart.js to JSDelivr CDN
        run: sed -i "s#main.dart.js#https://cdn.jsdelivr.net/gh/XMUMY/static@app-web/main.dart.js#" XMUX-Web/index.html
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_STATIC }}
          external_repository: XMUMY/static
          publish_branch: app-web
          publish_dir: ./XMUX-Web

  DeployFirebase:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: XMUX-Web
      - name: Replace main.dart.js to JSDelivr CDN
        run: sed -i "s#main.dart.js#https://cdn.jsdelivr.net/gh/XMUMY/static@app-web/main.dart.js#" XMUX-Web/index.html
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting:xmux-web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: xmux-app
