name: XMUX-Web

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/web.yaml
      - lib/**
      - web/**
      - pubspec.yaml
      - pubspec.lock

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build
        run: |
          echo $CONFIG_FILE | base64 -d > lib/config.dart
          export BUILD_NAME=`cat ./lib/config.sample.dart | grep fallbackVersionName | sed -e "s/[A-z=;' ]//g" | sed "s/-//g"` \
          export BUILD_NUMBER=`git rev-list HEAD --count`
          echo "version: $BUILD_NAME+$BUILD_NUMBER" >> pubspec.yaml
          flutter build web --release --source-maps
        env:
          CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
      - uses: actions/upload-artifact@v3
        with:
          name: XMUX-Web
          path: build/web

  DeployGithubStatic:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: XMUX-Web
          path: XMUX-Web
      - name: Replace main.dart.js to JSDelivr CDN
        run: sed -i "s#main.dart.js#https://cdn.jsdelivr.net/gh/XMUMY/static@app-web/main.dart.js#" XMUX-Web/index.html
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_STATIC }}
          external_repository: XMUMY/static
          publish_branch: app-web
          publish_dir: ./XMUX-Web

  DeployFirebase:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: XMUX-Web
          path: XMUX-Web
      - name: Replace main.dart.js to JSDelivr CDN
        run: sed -i "s#main.dart.js#https://cdn.jsdelivr.net/gh/XMUMY/static@app-web/main.dart.js#" XMUX-Web/index.html
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting:xmux-web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: xmux-app
