name: XMUX-Windows

on:
  push:
    branches:
      - master
    paths:
      - lib/**
      - windows/**
      - pubspec.yaml
      - pubspec.lock

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Build
        run: |
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String(${env:CONFIG_FILE})) > lib/config.dart
          git config --global core.longpaths true
          flutter config --enable-windows-desktop && flutter build windows --release
        env:
          CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
      - uses: actions/upload-artifact@v2
        with:
          name: XMUX-Windows
          path: build/windows/runner/Release
